---
jobs:
- name: deploy-release-tracker
  plan:
  - get: release-tracker
    trigger: true
  - put: cf
    params:
      path: release-tracker
      manifest: release-tracker/manifest.yaml

resources:
- name: release-tracker
  type: git
  source:
    uri: https://github.com/mattmcneeney/release-tracker
    branch: master

- name: cf
  type: cf
  source:
    api: ((CF_API))
    username: ((CF_USERNAME))
    password: ((CF_PASSWORD))
    organization: ((CF_ORGANIZATION))
    space: ((CF_SPACE))
